### ISSUE TITLE
Property value not reverted back after clicking discard on page

### ISSUE THREAD

**Issue by shaipetel** [SharePoint/sp-dev-training-spfx-webpart-proppane#25]
I've noticed a new bug in a web part we have, can anyone confirm and advise if it is occurring to them as well? I'm trying to rule out a bug in our code.

>Using SPFx 1.8.2 on SharePoint Online.

Scenario is pretty straight forward: a web part property that is updated using a custom designer (not in the built in property pane).

The property value is set using this code:
```
  private setPropertiesValue(propertyPath: string, newValue: any, skipRender: boolean = false) {
    const oldValue: any = get(this.properties, propertyPath);
    update(this.properties, propertyPath, () => newValue);
    if (skipRender !== true)
      this.render();
  }
```

the property value is a complex object ( not a string, something like {title:"hello", description:"welcome!"}  )

### Observed behavior
The bug we are noticing is this:
1. add the web part to the page, using setPropertiesValue  set this.properties.prop1 = {title: "hello v1"}
2. Save, publish, refresh - works as expected
3. edit the page, change the property using setPropertiesValue  set this.properties.prop1 = {title: "hello v2"} 
4. Click discard changes
5. The web part will display "hello v2" until the user refresh the page, then "hello v1" will be displayed

In edit mode, the webpart just renders 2 textboxes into its content and calling setPropertiesValue when the user changes their value.

#### Important to note
>When clicking discard, the constructor is called followed by OnInit.
>Checking this.properites during OnInit will show this.properties.prop1.title = "hello v2" which is the incorrect value, since the user discarded this change.

### Expected behavior
after clicking discard on the page I expected OnInit to be called with this.properties.prop1.title = "hello v1"

Any help, or confirmation if this issue happens/doesn't happen to you as well would be very helpful!
I was able to see this issue in several web parts, but some OOB web parts do not have this bug.

Thanks!

**Comment by andrewconnell** [comment]
This question is more about SPFx rather than an issue with this module. The SharePoint team doesn't monitor this repo as it's just a "hold" for the sample code in the associated Microsoft Learning module. Please submit your question to the appropriate SPFx developer support forum(s).
