### ISSUE TITLE
Error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by PrasadKasireddy** [SharePoint/sp-dev-training-spfx-webpart-proppane#7]
Two Property is added  under the interface.

export interface ISpFxProPaneWebPartProps {
  description: string;
  myContinent: string;
  numContinetVisited: number;
}

While run gulp server - I am getting Error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'. please refer the below screenshot.
![SPFxError](https://user-images.githubusercontent.com/11626905/62529966-4d4ef400-b85d-11e9-8275-6f9c2920e5dd.JPG)

**Comment by xgqfrms** [comment]
## How to fix the error in this situation?

```ts
function dailyTemperatures(temperatures: number[]): number[] {
  // ❌ error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
  // let answer = [...``.padEnd(temperatures.length, 0)].map(Number);
  // let answer = [...``.padEnd(temperatures.length, 0)].map(i => parseInt(i))!;
  //  ✅
  let answer = new Array(temperatures.length).fill(0);
  let stack = [];
  let count = 0;
  for(let i = 0; i < temperatures.length; i++) {
    while(stack.length && temperatures[stack[stack.length - 1]] < temperatures[i]) {
      let index = stack.pop();
      answer[index] = i - index;
    }
    stack.push(i);
  }
  return answer;
};
```

https://leetcode.com/problems/daily-temperatures/
